name: Trigger auto deployment for blitz-ui-docs-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [initial-architecture]
    paths:
      - '**'
      - '.github/workflows/blitz-ui-docs-container-app-AutoDeployTrigger-272d194e-9547-45fc-b5ac-7eac2860f965.yml'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BLITZUIDOCSCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BLITZUIDOCSCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BLITZUIDOCSCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.BLITZUIDOCSCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BLITZUIDOCSCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: blitz-ui-docs-container-app
          resourceGroup: blitz-ui
          imageToBuild: phillip.winder@icloud.com/blitz-ui-docs-container-app:${{ github.sha }}
